# Generated by Django 3.1.3 on 2020-11-12 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('ad_titel', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc_product', models.CharField(max_length=300)),
                ('wa_phone', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.URLField()),
            ],
        ),
    ]
